service_user: sensor
file_mode: "u=rw,g=r,o=r"
file_mode_executable: "u=rwx,g=rx,o=rx"
directory_mode: "u=rwx,g=rx,o=rx"
bin_dir: /usr/local/bin/sensor
bin_file: raspberry-pi-sensor
bin_url: "https://github.com/vzhurin/raspberry-pi-sensors-data-source/releases/download/{{ software_version }}/raspberry-pi-sensors-data-source-{{ software_version }}-linux-arm64"
software_version: 0.0.2
prometheus_metrics_port: 9101
